apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-kustomize-reconciler
  namespace: flux-bootstrap

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acme-kustomize-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: acme-kustomize-reconciler
    namespace: flux-bootstrap
---
