apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-releases-platform
  namespace: flux-bootstrap
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: acme-ssh-keypair
  timeout: 60s
  url: ssh://git@github.com/acme/k8s-releases-platform

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-releases-platform
  namespace: flux-bootstrap
spec:
  force: false
  interval: 10m0s
  prune: true
  serviceAccountName: acme-kustomize-reconciler
  sourceRef:
    kind: GitRepository
    name: k8s-releases-platform
    namespace: flux-bootstrap
